export const allProjects = [
    {
    id: 1,
    categore: ["react"],
    image: "/img/E-commerce.png",
    title: "E-commerce",
    desc: "Ecommerce Restaurant Website build with React ,ReactBoostarp the website is responsive in all screen",
    link: "https://fresh-cart-iota-liard.vercel.app/",
    github: "https://github.com/maryamhamdi/Fresh-Cart",
  },
  {
    id: 2,
    categore: ["react"],
    image: "/img/DermaMind.png",
    title: "DermaMind",
    desc: "An AI-powered skincare platform that provides skin analysis, personalized product  recommendations, an intelligent chatbot, and access to nearby dermatologists and pharmacies.",
    link: "https://derma-mind-3j78.vercel.app/",
    github: "https://github.com/maryamhamdi/DermaMind",
  },
   {
    id: 3,
    categore: ["react"],
    image: "/img/Recipe.png",
    title: "Recipe",
    desc: "Recipe website build React and Used API the website is responsive in all screen",
    link: " http://recipes-ten-kappa.vercel.app/",
    github: "https://github.com/maryamhamdi/Recipes-",
  },
  {
    id: 4,
    categore: ["js"],
    image: "/img/Weather.png",
    title: "Weather Project",
    desc: "Weather Project website build React and Used API the website is responsive in all screen",
    link: " https://weather-s86y.vercel.app/",
    github: "https://github.com/maryamhamdi/Weather-",
  },
    {
    id: 5,
    categore: ["js"],
    image: "/img/To-Do-List.png",
    title: "To do list",
    desc: "Simple Ecomerce Cart build with react , bootstrab and reduxtoolkit the website is responsive in all screen",
    link: "https://simplecart-67366.web.app/ ",
    github: "https://github.com/Mohammed-Omar-2003/simple_cart",
  },
   {
    id: 6,
    categore: ["js"],
    image: "/img/bookmark.png",
    title: "Bookmark",
    desc: "Simple bookmark build HTML,CSS and JS the website is responsive in all screen  ",
    link: "https://bookmark-three-zeta.vercel.app/",
    github: "https://github.com/maryamhamdi/bookmark",
  },
  {
    id: 7,
    categore: ["css"],
    image: "/img/Bakery.png",
    title: "Bakery",
    desc: "Website Restaurant build with HTML,CSS This website is Responsive in all screen",
    link: "https://bakery-three-pink.vercel.app/",
    github: "https://github.com/maryamhamdi/Bakery",
  },
  {
    id: 8,
    categore: ["css"],
    image: "/img/Fokir.png",
    title: "Fokir",
    desc: "Website A site to apply many tools within CSS, such as animation and so on. The site is responsive to all screens. build use HTML,CSS This website is Responsive in all screen",
    link: "https://fokir-orpin.vercel.app/",
    github: "https://github.com/maryamhamdi/Fokir",
  },
  // {
  //   id: 3,
  //   categore: ["css"],
  //   image: "/img/hc3.png",
  //   title: "Power GYM",
  //   desc: "Power GYM is a wibsite build with HTML and CSS the website is responsive in all screen",
  //   link: "https://mohammed-omar-2003.github.io/GYM/",
  //   github: "https://github.com/Mohammed-Omar-2003/GYM",
  // },
  // {
  //   id: 4,
  //   categore: ["bootstrap"],
  //   image: "/img/bs1.png",
  //   title: "Bondi",
  //   desc: "Bondi Website build with HTML,CSS and Bootstarp the website is responsive in all screen",
  //   link: "https://mohammed-omar-2003.github.io/Bondi/",
  //   github: "https://github.com/Mohammed-Omar-2003/Bondi",
  // },
  // {
  //   id: 5,
  //   categore: ["bootstrap", "js"],
  //   image: "/img/jsBs1.png",
  //   title: "Special Design",
  //   desc: "Website build HTML,CSS,JS,Bootstrap,DOM and Bom the website is responsive in all screen",
  //   link: "https://mohammed-omar-2003.github.io/template-js/",
  //   github: "https://github.com/Mohammed-Omar-2003/Bondi",
  // },
  // {
  //   id: 6,
  //   categore: ["bootstrap", "js"],
  //   image: "/img/jsBs2.png",
  //   title: " Clothes Shop ",
  //   desc: "Ecommerce Website shop build HTML,CSS,JS,Bootstrap,DOM and Bom the website is responsive in all screen",
  //   link: "https://mohammed-omar-2003.github.io/Ecommerce/",
  //   github: "https://github.com/Mohammed-Omar-2003/Ecommerce",
  // },

  // {
  //   id: 8,
  //   categore: ["js"],
  //   image: "/img/js2.png",
  //   title: "CRUDS",
  //   desc: "Product Management System build HTML,CSS and JS the website is responsive in all screen",
  //   link: "https://mohammed-omar-2003.github.io/CURD/",
  //   github: "https://github.com/Mohammed-Omar-2003/CURD",
  // },

  // {
  //   id: 12,
  //   categore: ["react"],
  //   image: "/img/react3.png",
  //   title: "Zakarne",
  //   desc: " A site that contains many services such as supplications, an electronic rosary, determining the direction of prayer, and knowing the prayer times .",
  //   link: "https://zakarne-72f8b.web.app/",
  //   github: "https://github.com/Mohammed-Omar-2003/azkar",
  // },
  // {
  //   id: 13,
  //   categore: ["react"],
  //   image: "/img/react4.png",
  //   title: "My Portfolio",
  //   desc: "My Portfolio contant  full my works Build With React ,React Bootstrap the website is responsive in all screen",
  //   link: "https://portfolio-360ed.web.app/",
  //   github: "لسه هرفعه على الجيت",
  // },

];
